{% set name = "Pint" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e98bdf01f4dcf840cc0207c0b6f7510d4e0c6288efc1bf470626e875c831172

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -v
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml

  run:
    - python >=3.8

test:
  imports:
    - pint
  commands:
    - pip check
    - python -c "import pint; ver = pint.__version__; assert ver != '0.0.0'"
    - pint-convert --help
  requires:
    - pip

about:
  home: https://github.com/hgrecco/pint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Operate and manipulate physical quantities in Python
  description: |
    Pint is a Python package to define, operate and manipulate physical
    quantities: the product of a numerical value and a unit of measurement.
    It allows arithmetic operations between them and conversions from and to
    different units. It is distributed with a comprehensive list of physical
    units, prefixes and constants. Due to its modular design, you can extend
    (or even rewrite!) the complete list without changing the source code.
    It supports a lot of numpy mathematical operations without monkey
    patching or wrapping numpy.
  doc_url: https://pint.readthedocs.org/
  dev_url: https://github.com/hgrecco/pint

extra:
  recipe-maintainers:
    - dopplershift
