{% set version = "0.7.1" %}

package:
  name: pint
  version: {{ version }}

source:
  fn: Pint-{{version}}.zip
  url: https://pypi.python.org/packages/source/P/Pint/Pint-{{version}}.zip
  md5: 1aa8d5188c6216cf42f0c7b7ea75ed07

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - pint

about:
  home: https://github.com/hgrecco/pint
  license: BSD
  summary: 'Physical quantities module'

extra:
  recipe-maintainers:
    - dopplershift
